### ISSUE TITLE
Cannot install Stylua v0.13.0

### ISSUE THREAD

**Issue by sid-maddy** [jc00ke/asdf-stylua#1]
**Describe the bug**

Stylua v0.13.0 removes the version from the release file names.

**Steps to reproduce**

`asdf install stylua 0.13.0`

**Expected behavior**

Stylua 0.13.0 is installed.

**Additional context**

Release: https://github.com/JohnnyMorganz/StyLua/releases/tag/v0.13.0
Issue: https://github.com/JohnnyMorganz/StyLua/issues/343#issuecomment-1085137654

**Comment by jc00ke** [comment]
Thanks for the heads up. I'm not sure when I'll get around to fixing this, but if you submit a PR that could speed up the resolution.

**Comment by sid-maddy** [comment]
Sure. I'll look into raising a PR tomorrow!
